name: Integration

on:
  push:
    branches:
      - 'develop'
  pull_request:
  repository_dispatch:
    types: [alfalfa-update]

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.13"
          
      - name: Start Alfalfa
        uses: TShapinsky/actions-alfalfa@main

      - name: Run tests with poetry and pytest
        run: |
          poetry install
          poetry run pytest -m integration